name: ll_env


channels:
        - defaults
        - conda-forge

dependencies:
- python == 3.13.0
- python.app
- numpy == 2.1.2
- pandas == 2.2.3
- matplotlib == 3.9.2
- seaborn == 0.13.2
- ipykernel == 6.29.5
- pingouin == 0.5.5
- pyqt == 5.15.11
- astropy == 6.1.4
- pyedflib == 0.1.38 
- pip
- pip:
  - git+https://github.com/aa-fisk/sleepPy.git@main
  - git+https://github.com/aa-fisk/actiPy.git@main
